=== harleyshi/flow-engine/flow-engine-core/src/main/resources/schema/flow-engine.xsd
<?xml version="1.0" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.w3school.com.cn"
           xmlns="http://www.w3school.com.cn"
           elementFormDefault="qualified">
    <xs:element name="engine">
        <xs:annotation>
            <xs:documentation><![CDATA[engines根对象]]></xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:choice minOccurs="2" maxOccurs="4">
                    <xs:element ref="engineName"/>
                    <xs:element ref="configParams"/>
                    <xs:element ref="pipeline"/>
                    <xs:element ref="script"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="engineName">
        <xs:annotation>
            <xs:documentation><![CDATA[定义一个engine]]></xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:attribute name="name" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <!-- 配置参数列表 -->
    <xs:element name="configParams">
        <xs:annotation>
            <xs:documentation><![CDATA[定义一个params]]></xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:choice minOccurs="1" maxOccurs="unbounded">
                    <xs:element ref="param"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <!-- 配置参数 -->
    <xs:element name="param">
        <xs:annotation>
            <xs:documentation><![CDATA[定义一个param]]></xs:documentation>
        </xs:annotation>
        <xs:complexType mixed="true">
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="desc" type="xs:string"/>
            <xs:anyAttribute namespace="##any" processContents="lax"/>
        </xs:complexType>
    </xs:element>

    <!-- 脚本   -->
    <xs:element name="script">
        <xs:annotation>
            <xs:documentation><![CDATA[定义一个script。]]></xs:documentation>
        </xs:annotation>
        <xs:complexType mixed="true">
            <xs:attribute name="name" type="xs:string" use="required">
                <xs:annotation>
                    <xs:documentation><![CDATA[标识脚本，Spring环境下name可以为相应的bean名称]]></xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute name="type" type="xs:string">
                <xs:annotation>
                    <xs:documentation><![CDATA[script类型，例如QLExpress、OGNL等, 或者填写类全称限定名，Spring环境下可不填写该字段]]></xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:anyAttribute namespace="##any" processContents="lax"/>
        </xs:complexType>
    </xs:element>

    <!-- 通用属性组 -->
    <xs:attributeGroup name="commonAttributeGroup">
        <xs:attribute name="ignoreException" type="xs:boolean" default="false"/>
        <xs:attribute name="timeout" type="xs:int"/>
    </xs:attributeGroup>

    <!-- pipeline节点属性组 -->
    <xs:attributeGroup name="pipelineAttributeGroup">
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="desc" type="xs:string"/>
        <xs:attribute name="async" type="xs:boolean" default="false"/>
        <xs:attributeGroup ref="commonAttributeGroup"/>
    </xs:attributeGroup>

    <!-- 普通节点属性组 -->
    <xs:attributeGroup name="nodeAttributeGroup">
        <xs:attribute name="desc" type="xs:string"/>
        <xs:attribute name="operator" type="xs:string" use="required"/>
        <xs:attribute name="params" type="xs:string"/>
        <xs:attribute name="rollback" type="xs:string"/>
        <xs:attribute name="rollbackParams" type="xs:string"/>
        <xs:attributeGroup ref="commonAttributeGroup"/>
    </xs:attributeGroup>

    <xs:element name="pipeline">
        <xs:annotation>
            <xs:documentation><![CDATA[定义一个pipeline]]></xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:choice minOccurs="1" maxOccurs="unbounded">
                    <xs:element ref="pipeline"/>
                    <xs:element ref="component"/>
                    <xs:element ref="if"/>
                    <xs:element ref="choose"/>
                </xs:choice>
            </xs:sequence>
            <xs:attributeGroup ref="pipelineAttributeGroup"/>
            <xs:anyAttribute namespace="##any" processContents="lax"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="component">
        <xs:annotation>
            <xs:documentation><![CDATA[定义一个节点。]]></xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:attributeGroup ref="nodeAttributeGroup"/>
            <xs:anyAttribute namespace="##any" processContents="lax"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="if">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="then" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="else" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute name="test" type="xs:string" use="required">
                <xs:annotation>
                    <xs:documentation><![CDATA[条件判断对象]]></xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attributeGroup ref="commonAttributeGroup"/>
            <xs:anyAttribute namespace="##any" processContents="lax"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="then">
        <xs:annotation>
            <xs:documentation><![CDATA[必须与if结合使用。]]></xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element ref="pipeline"/>
                    <xs:element ref="component"/>
                    <xs:element ref="if"/>
                    <xs:element ref="choose"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="else">
        <xs:annotation>
            <xs:documentation><![CDATA[必须与if结合使用。]]></xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element ref="pipeline"/>
                    <xs:element ref="component"/>
                    <xs:element ref="if"/>
                    <xs:element ref="choose"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- choose -->
    <xs:element name="choose">
        <xs:annotation>
            <xs:documentation><![CDATA[switch控制流。]]></xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="case" minOccurs="2" maxOccurs="unbounded"/>
                <xs:element ref="default" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute name="test" type="xs:string" use="required">
                <xs:annotation>
                    <xs:documentation><![CDATA[条件判断对象]]></xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attributeGroup ref="commonAttributeGroup"/>
            <xs:anyAttribute namespace="##any" processContents="lax"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="case">
        <xs:annotation>
            <xs:documentation><![CDATA[必须与when结合使用。]]></xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence >
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element ref="pipeline"/>
                    <xs:element ref="component"/>
                    <xs:element ref="if"/>
                    <xs:element ref="choose"/>
                </xs:choice>
            </xs:sequence>
            <xs:attribute name="when" type="xs:string" use="required">
                <xs:annotation>
                    <xs:documentation><![CDATA[当值为指定值时，进入该分支。]]></xs:documentation>
                </xs:annotation>
            </xs:attribute>
        </xs:complexType>
    </xs:element>

    <xs:element name="default">
        <xs:annotation>
            <xs:documentation><![CDATA[必须与when结合使用。]]></xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence >
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element ref="pipeline"/>
                    <xs:element ref="component"/>
                    <xs:element ref="if"/>
                    <xs:element ref="choose"/>
                </xs:choice>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== harleyshi/flow-engine/flow-engine-demo/flow-engine-demo-springboot/target/classes/flow/order/flow-create-order.xml
<?xml version="1.0" encoding="UTF-8"?>
<engine xmlns="http://www.w3school.com.cn"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.w3school.com.cn flow-engine.xsd">
    <engineName name="createOrder"/>
    <configParams>
        <param name="paramsCheck">
            {
            "orderId": "123456789"
            }
        </param>
        <param name="rollbackParamsCheck" desc="订单是否来自购物车"></param>
    </configParams>

    <script name="scriptTest">
        System.out.println("invoke scriptTest");
        int a = 1;
        int b = 12;
        boolean result = "123456".equals(ctx.orderId);
        return true;
    </script>

    <pipeline name="createOrder" desc="创建订单流程">
        <component operator="paramsCheck" params="paramsCheck" desc="参数检查" rollback="rollbackParamsCheck"/>
        <pipeline name="getOrderInfo" desc="组装订单信息" async="true">
            <component operator="queryGoodsInfo" desc="查询商品信息" rollback="rollbackQueryGoodsInfo"/>
            <component operator="queryShipping" desc="查询运费信息"/>
            <component operator="queryUserAddress" desc="查询用户地址信息"/>
            <component operator="queryStoreInfo" desc="查询店铺信息"/>
        </pipeline>
        <if test="scriptTest" ignoreException="true">
            <!--                    <if test="orderFromShoppingCart">-->
            <then>
                <component operator="removeCart" desc="移除购物车选中的商品"/>
            </then>
        </if>
        <component operator="deductStock" desc="扣减库存(发生异常回滚库存)" rollback="releaseStock"/>
        <component operator="builderOrderInfo" desc="构建订单信息"/>
        <component operator="saveOrderInfo" desc="保存订单信息到数据库（包含子单）"/>
        <component operator="syncOrderToEs" desc="同步订单到ES"/>
        <component operator="saveOrderLog" desc="保存订单日志"/>

    </pipeline>
</engine>
